### ISSUE TITLE
Can't initialize connection to redis server

### ISSUE THREAD

**Issue by yarosman** [sergkh/redis-client-scala-netty#5]
await_() in I/O thread causes a dead lock or sudden performance drop. Use addListener() instead or call await_() from a different thread.

1) Error injecting constructor, java.lang.IllegalStateException: await_() in I/O thread causes a dead lock or sudden performance drop. Use addListener() instead or call await_() from a different thread.
  at security.ConfirmationCodeService.<init>(ConfirmationCodeService.scala:35)
  while locating security.ConfirmationCodeService
    for parameter 6 at controllers.UserController.<init>(UserController.scala:33)
  while locating controllers.UserController

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
    at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$13$$anonfun$apply$13.apply(Routes.scala:2849) ~[na:na]
    at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$13$$anonfun$apply$13.apply(Routes.scala:2849) ~[na:na]
    at play.core.routing.HandlerInvokerFactory$$anon$12$$anon$13.call(HandlerInvoker.scala:89) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.core.routing.TaggingInvoker.call(HandlerInvoker.scala:32) ~[play_2.11-2.4.6.jar:2.4.6]
    at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$13.apply(Routes.scala:2849) ~[na:na]
    at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$13.apply(Routes.scala:2848) ~[na:na]
    at scala.util.Either.fold(Either.scala:99) [scala-library-2.11.7.jar:na]
    at play.core.routing.GeneratedRouter.call(GeneratedRouter.scala:99) ~[play_2.11-2.4.6.jar:2.4.6]
    at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:2848) ~[na:na]

**Comment by sergkh** [comment]
Found some [article](http://nitschinger.at/Never-await-Uninterruptibly-on-Netty-Channels/) that clarifies why this happens

**Comment by yarosman** [comment]
Thanks for article

**Comment by sergkh** [comment]
Fix already in master
